name: 'test_dbt'
version: '1.0.0'
config-version: 2

profile: 'test_dbt'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
log-path: "~/"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  test_dbt:
    example:
      +materialized: view