name: Publish Docker image

on:
  push:
    branches: [master]

env:
  DOCKER_HUB_NAMESPACE: dhume
  DOCKER_HUB_REPOSITORY: corise-dagster

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    strategy:
      matrix:
        target:
          - dagit
          - daemon
          - week_2
          - week_3_4_content
          - week_3_4_project
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_HUB_NAMESPACE }}/${{ env.DOCKER_HUB_REPOSITORY }}
          tags: |
            ${{ matrix.target }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          target: ${{ matrix.target }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Will be overridden by the volume mount
          build-args: |
            COURSE_WEEK=week_3